### ISSUE TITLE
v0.7 upgrade guide

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1218]
To ease the the update from 0.6 to 0.7 we should write an upgrade guide.

Related #1217.

**Comment by guiri14** [comment]
A small addition but PollOpt no longer exists because Mio only supports edge triggers now, so that's removed when upgrading (if you only use edge events.. not sure you can do much in the other case).

**Comment by Thomasdezeeuw** [comment]
I don't really have too much time to write this but I don't want to wait with a v0.7 release any longer. So I would refer to the blog post I made: https://tokio.rs/blog/2019-12-mio-v0.7-alpha.1.

**Comment by Thomasdezeeuw** [comment]
Removing from v0.7 milestone to not block the release.

**Comment by koutheir** [comment]
Is there any reason why non-edge events were removed? e.g., level events.

**Comment by Thomasdezeeuw** [comment]
@koutheir #928 is the related issue, TL;DR level and one-shot triggers were broken on some platforms, instead we've opted to (for now) only support edge triggers.

**Comment by tormol** [comment]
A gotcha I found about selectively enabling mio 0.7 features in a library:

Because of [Cargo bug #4866](https://github.com/rust-lang/cargo/issues/4866), enabling more features as dev-dependency will also enable that feature for users of the crate, where `[dev-dependencies]` should normally be ignored. This means that for example

```toml
[dependencies]
mio = {version="0.7.0", features=["os-util"]}

[dev-dependencies]
mio = {version="0.7.0", features=["os-poll"]}
```

is equivalent to

```toml
[dependencies]
mio = {version="0.7.0", features=["os-util", "os-poll"]}
```

and that a dependent crate which didn't enable os-poll itself but only specified

```toml
[dependencies]
mio = "0.7"
library_extending_mio = "x.y.z"
```

will stop compiling when that bug is fixed.

In the meantime one can use [`cargo -Zfeatures=dev_dep`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#features) to check that one doesn't depend on more than has been specified.
