### ISSUE TITLE
could not find `unix` in `mio`

### ISSUE THREAD

**Issue by chengshuyi** [tokio-rs/mio#1509]
Hi,

I encountered this problem using mio on linux.

Problem : could not find `unix` in `mio`.
Corresponding code:use mio::unix::SourceFd;
mio version is : mio = "0.7".

other info.

```$rustc -V --verbose
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.53.0
LLVM version: 12.0.1
```

Thanks.

**Comment by memoryruins** [comment]
The `os-ext` feature needs to be enabled:
```toml
[dependencies]
mio = { version = "0.7", features = ["os-ext"] }
```
